name: Build CMake-based Project

on: [ push, pull_request, merge_group ]

jobs:
  build_and_test_regular:
    name: build + test (regular)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup GCC
        run: g++-10 --version || true
      - run: g++-11 --version || true
      - run: g++-12 --version || true
      - run: g++-13 --version || true

  build_and_test_nix:
    name: build + test (Nix)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build . # Build the default Flake attribute.
